### ISSUE TITLE
Interior Label for inner rings displays Total, Tested, and Conformance Tested

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#156]
# Request: Every ring save the outermost will display three data points: total endpoints within the ring, total percentage of these endoints that are tested, and total percentage that are tested by a Conformance test
## Short description:

- Current state:
  - Inner Labels show total and tested only, and it is unclear how many are conformance tests
- Desired state:
  - The percentage of endpoints hit by conformance tests is clearly indicated in inner ring.

### Tasks:
- [ ] Review current method of calculating total and tested, and refine if necessary
- [ ] add total conformance tests to this above method
- [ ] Add section to interiorlabel of sunburst to account for endpoint coverage.

**Comment by zachmandeville** [comment]
THis has been implemented i work around #161.  Interior ring shows # of endpionts, % hit by tests, % hit by conformance tests.  When hovering over a single endpoint, you see either:
- "tested, not conformance tested"
- "tested and conformance tested"
- "untested"
