### ISSUE TITLE
Ensure "isTested" specifically means e2e.test hit endpoint

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#158]
# Request: Ensure the endpoint key "isTested" shows as true only if e2e.test hits that endpoint.

## Short description:

- Current state:
  - Logic is the same between <=1.11 and >=1.12 
- Desired state:
  - Logic is changed to account for useragent being available 1.12 and above.

### Tasks:
- [x] Review logic in backend.org
- [x] Review logic in `data-gen/processAuditLog.py`
- [x] adjust both as needed.

**Comment by zachmandeville** [comment]
This has been corrected in the work around #161 .  There are now testHits, and conformanceTestHits and both are just a counter.  We can tell if an endpoint is tested by whether it's testHits counter is greater than 0.
