### ISSUE TITLE
Create app.org: a prototype of the site running without feathers backend

### ISSUE THREAD

**Issue by devaii** [cncf/apisnoop#161]
# Request: Begin org file, which tangles into site, that shows how apisnoop could work loading from json files instead of pinging the feathers backend

## Short description:

- Current state:
  -We have discussed this change in architecture for the site, but have not explored it through coded.  We are in need of a central code discussion point to see where to move forward
- Desired state:
  - a simple app.org is created that tangles into a simple, workable site, which begins that discussion/exploration
### Tasks:
- [x]  create app.org branch based off master.
- [x] app.org bundles into basic development environment with header, footer, message.
- [x] client.org code brought into new .org, but commented out so we can add each part in intentionally.
- [x] job-result info (job, bucket, release, timestamp) added as new header, pulling from json.
- [x] endpoints refactored to account for not needing release info anymore.
- [x] sunburst displays upon page load.
- [x] tests are added to app
- [x] useragents are added to app
- [x] test sequences are added to app
- [x] test_tags are added to app
- [x] summary information shows upon hover of endpoint
- [x] filter by useragent that match a regex available
- [x] tests that hit an endpoint displayed when hovering over valid endopint
- [x] clicking  on a test shows its test sequence

**Comment by zachmandeville** [comment]
began work which you can see in the `app.org` branch.  there's a new folder called `app` with an `app.org` file within.

**Comment by zachmandeville** [comment]
all tasks implemented in #171
