### ISSUE TITLE
Document Developing the APISnoop spyglass lens

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#167]
# Request: local dev prow instance to allow exploration of spyglass lens

## Short description:

- Current state:(Description of _desired_ state.)
  - No spyglass lens dev env
- Desired state:
  - Any developer can pull our branch and explore APISnoop data

### Tasks:
- [x] create branch of test-infra
- [x] create gcs buckets for apisnoop data
- [ ] create new prow jobs modelled after current conformance jobs
- [ ] update the deck config to show the new apisnoop job output buckets
- [ ] update the deck config for simple spyglass lens to pull simply list the apisnoop json files
- [ ] ensure @zachmandeville can use documentation to pull down and start integrating his single html files (plus static assets) approach

**Comment by hh** [comment]
@zachmandeville can you verify that the documentation works for you and bring it into  the repo.

**Comment by zachmandeville** [comment]
verified!  looks good.
