### ISSUE TITLE
Literately go from bare metal to kind+kubetest

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#168]
Put together an literate org (and it's md)

### Tasks:
- [ ] Provision Packet (or use local box)
- [ ] X

**Comment by heyste** [comment]
**Tasks:**

- [ ] Provision hardware 
  - Use Packet or local box
- [ ] Install dependencies
  - docker
  - git & gcc
  - go
  - kubectl
- [ ] Download core software 
  - kubernetes
  - kubetest
  - kind
- [ ] Provision kubernetes cluster
  - Build kubetest
  - Provision cluster via kubetest
- [ ] Health checks
  - docker
  - kubernetes

**Comment by hh** [comment]
@hestye we will need the kubetest parameters to run kind based tests and also extract the audit-logs:

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kind/kind.yaml#L130

```
# conformance test against kubernetes master branch with `kind`, skipping
# serial tests so it runs in ~20m
- interval: 20m
  name: ci-kubernetes-kind-conformance-parallel
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
      env:
      # skip serial tests and run with --ginkgo-parallel
      - name: "PARALLEL"
        value: "true"
      args:
      - "--job=$(JOB_NAME)"
      - "--root=/go/src"
      - "--repo=k8s.io/kubernetes=master"
      - "--repo=sigs.k8s.io/kind=master"
      - "--service-account=/etc/service-account/service-account.json"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./../../sigs.k8s.io/kind/hack/ci/e2e.sh"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m

```

**Comment by heyste** [comment]
- Initial setup of docker, kind and kubetest covered in this [document](https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/setup-kubetest-kind-on-packet.org) which creates this [script](https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/setup-kubetest.sh).
- Testing kubernetes with kind and kubetest is covered in this [document](https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/testing-kubernetes-with-kind-kubetest.org).
- @hh [Running a single test](https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/testing-kubernetes-with-kind-kubetest.org#running-a-single-test) almost solved but I think my [run_tests function](https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/testing-kubernetes-with-kind-kubetest.org#setup-and-export-function-run_tests) is having an issue with the word 'conformance' for some reason.

**Comment by hh** [comment]
Here is a very simple iteration loop that takes 7 seconds to focus on one test.
I think it might be good to follow a simpler approach sans the bash function ala:

https://github.com/cncf/apisnoop/blob/kubetest-docs/docs/testing-kubernetes-with-kind-kubetest.org#with-bazel

This seems like the quickest direct route to getting a cluster up using the current master checkout:
```
cd ~/go/src/k8s.io/kubernetes
kind build node-image --base-image kindest/base:latest --kube-root .
kind create cluster --image kindest/node:latest
export GINKO_PARALLEL=y
export KUBECONFIG="$HOME/.kube/kind-config-kind-kubetest"
TEST_NAME='[sig-cli] Kubectl client [k8s.io] Kubectl get componentstatuses should get componentstatuses'
echo $TEST_NAME
# Here we are escaping the [] and replacing each space with a .
# [ => \[
# ] => \]
# :space: => .
FOCUS=$(echo "$TEST_NAME" \
  | sed "s/\[/\\\[/g" \
  | sed "s/\]/\\\]/g" \
  | sed "s/[[:space:]]/\./g")
echo $FOCUS
```

The following loop takes about 7 seconds and only runs one test:
```
bazel build //test/e2e:e2e.test
PREFIX=./bazel-bin/test/e2e
$PREFIX/e2e.test \
  --ginkgo.focus="$FOCUS"
```

**Comment by hh** [comment]
@zachmandeville was able to use the literate documentation from @heyste to only spend 30 minutes to get a from source cluster up and running for writing conformance tests.
Thanks everyone for the hard work!
