### ISSUE TITLE
APISnoop Spyglass initial Lens Loading

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#177]
# Request: use documentation to pull down and start integrating simple APISnoop html files 

(plus static assets) approach

## Short description:

- Current state:
  - [x] npm build creates static files that use a bucket
  - [x] ./runlocal allows for local apisnoop spyglass lens development
- Desired state:
  - [ ] ./runlocal w/ apisnoop lense displays apisnoop static files (defaulting to the bucket it serves)

### Tasks:
- [ ]

**Comment by hh** [comment]
We'd like the browser to be able to retrieve our json artifacts directly (apisnoop) from another gcs location.

This works if we visit our lens iframe directly:

http://ii.cncf.ci:8080/spyglass/lens/apisnoop/iframe?req=%7B%22artifacts%22%3A%5B%22finished.json%22%2C%22started.json%22%5D%2C%22src%22%3A%22gcs%2Fkubernetes-jenkins%2Fpr-logs%2Fpull%2F76459%2Fpull-kubernetes-node-e2e%2F1120457851848888332%22%7D

However we are getting the following error in the browser console if we visit via the the spyglass page:

http://ii.cncf.ci:8080/view/gcs/kubernetes-jenkins/pr-logs/pull/76459/pull-kubernetes-node-e2e/1120457851848888332/

```
Access to fetch at 'http://storage.googleapis.com/apisnoop/spyglass/ci-kubernetes-e2e-gci-gce/1116453304528801792/test_sequences.json' from origin 'null' has been blocked by CORS policy:
The 'Access-Control-Allow-Origin' header has a value 'http://ii.cncf.ci:8080' that is not equal to the supplied origin.
Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Looks like we'll need to explore how to get the iframes to send a CORS policy header.

I asked this in #prow on k8s slack: [here](https://kubernetes.slack.com/archives/CDECRSC5U/p1555991719114600)

@Katharine have you had to deal with CORS yet with spyglass?

**Comment by hh** [comment]
Katharine via chat:
> Use the lens callback handler to request information from GCS.
> That said, I don't think the current server-side lens API exposes a GCS client
> except for known artifacts, so you'll probably have to
> just make an HTTP request yourself or something

From https://github.com/kubernetes/test-infra/blob/master/prow/cmd/deck/static/spyglass/lens.ts#L22 :
```javascript
  /**
   * Sends a request to the server-side lens backend with the provided data, and
   * returns a promise that will resolve with the response as a string.
   *
   * @param data Some data to pass back to the server. JSON encoding is
   *             recommended, but not required.
   */
  request(data: string): Promise<string>;
```

**The request could be for each GCS bucket/obect json we need to load**

Existing usage via https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/lenses/buildlog/buildlog.ts#L55 for loading more lines when hitting  'show skipped'

```javascript
async function handleShowSkipped(this: HTMLDivElement, e: MouseEvent) {
 ...
  const {artifact, offset, length, startLine} = this.dataset;
  const content = await spyglass.request(JSON.stringify({
    artifact, length: +length!, offset: +offset!, startLine: +startLine!}));
  this.innerHTML = ansiToHTML(content);
  showElem(this);
...
  spyglass.contentUpdated();
}
```

The buildlog lens Calback https://github.com/kubernetes/test-infra/blob/master/prow/spyglass/lenses/buildlog/lens.go#L146

**This is where we could provide the proxy request.**

```go	if !ok {
		return "no artifact named " + request.Artifact
	}
// Callback is used to retrieve new log segments
func (lens Lens) Callback(artifacts []lenses.Artifact, resourceDir string, data string) string {
	var request LineRequest
	err := json.Unmarshal([]byte(data), &request)
        // ...
	artifact, ok := artifactByName(artifacts, request.Artifact)
       // ...

	var lines []string
	if request.Offset == 0 && request.Length == -1 {
		lines, err = logLinesAll(artifact)
	} else {
		lines, err = logLines(artifact, request.Offset, request.Length)
	}
	if err != nil {
		return fmt.Sprintf("failed to retrieve log lines: %v", err)
	}

	logLines := highlightLines(lines, request.StartLine)
	return executeTemplate(resourceDir, "line group", logLines)
}
```

**Comment by hh** [comment]
Let's try:
```
add `*` to the list of allowed origins, which I'm reasonably sure would work
```

**Comment by hh** [comment]
@devaii can you review and see what's missing for this?
And if nothing, please comment and close.

**Comment by devaii** [comment]
We have it so that `./runlocal` with the APISnoop lens enabled displays a static APISnoop page (in iframe). Default bucket logic is not yet implemented.

**Comment by hh** [comment]
We now have netlify, which has a preview mode.
The resulting netlify site is static, which met the needs of this ticket.
