### ISSUE TITLE
list of buckets appear at top of page, instead of on their own page.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#183]
# Request: Bring the bucket list to the top of the page, as it was before.

## Short description:

- Current state:
  - a list of five buckets are on an unstyled starting page.
- Desired state:
  - This list matches the look from  before re-architecture, where they were in styled boxes at top of page.

### Tasks:
- [ ] Bring routing omponent from client.org back to app.org
- [ ] Display it based on our bucketlist bundle instead of possible routes.
- [ ] clicking on the bucket updates the query param for bucket, and triggers a refresh.
- [ ] there is a loading state inbetween switches, as data repopulates.

**Comment by zachmandeville** [comment]
implemented in fefa566b7108b5cbaf02aca4bb162438b80f0da0 and part of #181
