### ISSUE TITLE
Ensure Netlify pipeline functions for each branch of site

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#184]
# Request: Our netlify deployment shows a built and functioning apisnoop for each branch we have open.

## Short description:

- Current state:
  - It is unverified that it is working.
- Desired state:
  - We have documented that it works, or made a list of steps needed to get it functional.

### Tasks:
- [x] make sure all devs (zach) has admin access to netlify.
- [x] ensure a build step is built into netlify hook.
- [x] ensure netlify is serving apisnoop from the build folder.
- [x] test how this works for a branch other than master.

**Comment by zachmandeville** [comment]
the latest changes i pushed for the buckelist branch show up at https://5cc233cf2f18f500096a7f9f--apisnoop.netlify.com/.  So this seems to be working.

The master branch is showing a sit, but without data.  I think this has to do with the code on the master branch and not the pipeline.
