### ISSUE TITLE
Site has Aesthetic Appeal

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#185]
# Request: update the aesthetic papercuts of the site

## Short description:

- Current state:
  - there are a number of small flourishes we could add to help usability and appeal of site.
- Desired state:
  - site is aesthetically appealing and usable.

### Tasks:
- [x] add source (like prow.k8s.io) to our audit-sources.yaml, and then show source at top
- [x] remove 'select a bucket' as title
- [x]  bucketlist is just bucket and job.
- [x] generate link back to prow job.
- [x] add a link to spyglass/prow beneath title.
- [x] in endpoints summary, less padding between title and test list
- [x] in tests summary, list of tests are not centered.
- [x] in Bucketlist, Active Bucket is a different color from rest.
- [x] filters are not listed in column, but all on same row.
- [x] filter section is tighter, where you can click a button for type of filter, which brings up the search bar.

**Comment by zachmandeville** [comment]
this is  a cathcall ticket of sorts, to track  the aesthetic improvements we notice as we work on other tickets.

**Comment by zachmandeville** [comment]
Implemented as part of #201
