### ISSUE TITLE
Documentation Using kind to write Tests

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#189]
# Request: Pair session with Globant

## Short description:

- Current state:
  - We have our pair environment, and initial documentation
- Desired state:
  - Document speedups and improvements to testing loop

### Tasks:
- [x] Schedule Pair Session for Monday
- [ ] Document existing creation test process, and speed improvements
- [ ] Upstream to appropriate repo

Related:
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md
- https://github.com/ii/org/blob/master/research/setup-kubetest-kind-on-packet.org

We have the shared packet env, which greatly helps reduce build/test loop times. Let's enable and document the speedups by using kind builds to write e2e test.

/cc @mgdevstack

**Comment by hh** [comment]
@heyste you're welcome to join, but it's at 3am NZT

**Comment by zachmandeville** [comment]
this process has become a key part of apisnoop in the cluster, as illustrated in test tickets coming from ii and people using apisnoop.  Due to the age of this ticket, and that it is more of a reminder to meet, I think it is safe to close.
