### ISSUE TITLE
Ensure PRs to APISnoop generate data

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#190]
# Request: Enable others to contribute data processing and UI within a single PR

## Short description:

- Current state:
  - Manual updates of test-grid source buckets
  - Manual generate of target data
  - Manual upload of target data to gs://apisnoop/
- Desired state:
  - PR can update the source buckets
  - Prow Job will generate target data
  - Job will upload results to GCS

### Tasks:
- [x] Locate credentials for uploading to GCS
- [x] Ensure those creds are available via Prow
- [x] Create prow job to react PR and run simple job
- [x] expand job (create container) to process
- [x] decorate job to upload results to GCS

**Comment by hh** [comment]
PRs update data, now we need to ensure the data generated for a specific commit on a PR is correctly linked to it's netlify preview deploy.

**Comment by hh** [comment]
From here we head to #159
