### ISSUE TITLE
Write regexp filter to highlight Globant

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#191]
# Request: Write regxep focused on tests updated by Globant

## Short description:

- Current state:
  - No view into Globant
- Desired state:
  - A view into seeing Globant productivity
  - A easier view for others to model / search

### Tasks:
- [ ]  List generated (scripted would be great, manual works too) 

- [ ]  Generate regexp for the list for use with existing APISnoop urls
OR if the list is quite long, or the regexp won't work, then
- [ ]  Create branch with updated code to tag tests as globant work based on their list

**Comment by mgdevstack** [comment]
I have list of Issue numbers handy where we have added contributions but I'm not sure how easy it would be to show on APISnoop specially when we look for, By which % API coverage has been improved and different areas of contribution. 

https://github.com/issues?utf8=%E2%9C%93&q=involves%3Apontiyaraja+involves%3Amgdevstack+involves%3Aglobervinodhn+archived%3Afalse+sort%3Aupdated-desc

**Comment by hh** [comment]
Thanks for the search @mgdevstack 
We'll use this to verify our ongoing work working with querying github issues, PRs, and the board.
