### ISSUE TITLE
Documentation for kubeadm config for creating audit logs in $ARITFACT/ => GCS

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#203]
# Request: (Put request here. One liner.)

## Short description:

- Current state:
  - We depend on upstream audit log generation for GCS only
- Desired state:
  - Anyone can create a prow job that copies the $ARTIFACTS into GCS for processing via APISnoop for their non-google cloud

### Tasks:
- [ ] Setup Prow Job that builds, deploys, and runs conformance test on GCS
- [ ] Update and document the creation of the kubeadm configs that generate audit-logs
- [ ] Update and document the copying of $ARTIFACTS into GCS

**Comment by zachmandeville** [comment]
@hh, can you elaborate on this request?

**Comment by hh** [comment]
Elaborations added.
/cc @zachmandeville

**Comment by Riaankl** [comment]
Issue Closed: Stale / Clean-up
