### ISSUE TITLE
Select Bucket/Job through compact dropdown

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#214]
# Request: A more aesthetically appealing, and compact, way to select your audit log.

## Short description:

- Current state:
  - We list each bucket/job as a box to click, and at the top of the site.
- Desired state:
  - This is held within a single dropdown, with the real estate of the t op of the site given to introductory text or some other better design.

### Tasks:
- [ ] agree upon new design of frontend
- [ ] decide where dropdown lives in this design
- [ ] design dropdown
- [ ] reimplement bucketlist component to be designed dropdown
- [ ] incorporate this component in new design.

**Comment by zachmandeville** [comment]
implemented in #233
