### ISSUE TITLE
Move filters to more meaningful location

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#216]
# Request: implement filters to match our new design

## Short description:

- Current state:
  - filters are placed without much context at top of site.
- Desired state:
  - filters are grouped in a meaningful, aesthetically appealing location.  Perhaps within a sidebar like landscape.cncf.io

### Tasks:
- [ ] agree upon new design of frontend
- [ ] implement filter container matching new design.
- [ ] incoprorate new component into app.

**Comment by zachmandeville** [comment]
We are going with a sidebar for the immediate moment, but will do more intentional design upon user feedback.

**Comment by zachmandeville** [comment]
implemented in #233
