### ISSUE TITLE
Netlify builds should wait until the parallel Prow job is finished

### ISSUE THREAD

**Issue by devaips** [cncf/apisnoop#235]
# Request: Add logic to make Netlify jobs wait until Prow job is complete

## Short description:
When there is a new push or PR, both Prow and Netlify jobs are triggered. Netlify jobs are quicker, and will pull the `latest-job.txt` before the Prow job has had time to update it. We need to have the Netlify job poll Prow to find out when the job is finished. Temporary mitigation could be to add a `sleep $x` to the Netlify jobs.

- Current state:
  - Netlify jobs do not wait for the latest job to finish.
- Desired state:
  - Netlify waits for the parallel Prow job to finish, and then pulls the `latest-job.txt` 

### Tasks:
- [x] Implement `sleep` for temp fix
- [ ] Research how to best poll for the Prow job progress
- [ ] Implement logic to wait for Prow job

**Comment by hh** [comment]
Roughly 19-21 minutes:

Postsubmit / Master branch: http://prow.cncf.ci/?repo=cncf%2Fapisnoop&type=postsubmit
PreSubmit / PRs: http://prow.cncf.ci/?repo=cncf%2Fapisnoop&type=presubmit

**Comment by devaii** [comment]
Temp added at https://github.com/cncf/apisnoop/commit/66f32943c4132f42343a1fc72ad06818acbad49b

**Comment by hh** [comment]
The primary driver here, was netlify PR sites not loading at all and we fixed the majority of these issues by not generating new data every time, only when files under ./data-gen/ were modified.

When we do generate new data, nelify uses the most recent data and requires a second commit or manually triggered netlify job to update to point to the new data.

It's a reasonable compromise for now.
