### ISSUE TITLE
Toggle Sunburst to show only untested, tested, and/or conformance tested.

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#244]
# Request: When viewing the sunburst, be able to quickly reduce its display to one of the three states

## Short description:
- Current state:
  - Sunburst shows all three types of endpoints, color-coded to differentiate.  there is no way to redue down.
- Desired state:
  - a checkbox in bottom left of sunburst that lets you toggle which type you want to see.  This updates the url, so your exact filters are always sharable.

### Tasks:
- [ ] Add a query param for this toggle 
- [ ]  filter endpoints by this query param.
- [ ]  create component that sets this query param.

**Comment by zachmandeville** [comment]
implemented in #245
