### ISSUE TITLE
Display list of all visible endpoints to offer alternate overall view

### ISSUE THREAD

**Issue by zachmandeville** [cncf/apisnoop#246]
# Request: when not zoomed into a single endpoint, show a list of all visible endpoints as alternate option alongside sunburst.

## Short description:

- Current state:
  - We only show the sunburst, and the current path.
- Desired state:
  - when not zoomed in, or zoomed into level or category, offer a list, below the sunburst, showing all included endpoints, whether they're tested or not, and their group, kind.

### Tasks:
- [ ] Add a Basic <EndpointList /> Component to our Main View, visible only when there is no zoom, or zoom !== 'endpoint'
- [ ] populate this list with endpoint names and their tested status.
- [ ] add add'l info (group, kind, level)
- [ ] sort by level, then group, then kind, then untested, tested, conformance-tested.

**Comment by zachmandeville** [comment]
completed as part of #248
